### ISSUE TITLE
Blocking Guests Tenants to view user list.

### ISSUE THREAD

**Issue by manshu** [LaravelDaily/Landlord-Tenants-Laravel#1]
I was spending time to checkout your code, and found out that the route to /admin/users is open to anyone. I'd would like to learn how to block guest users to not view the users page. Would love to see a video explaining this, and get more insight on middleware using permissions/roles.

Thanks 👍

**Comment by LaravelDaily** [comment]
@manshu thank you, indeed I forgot some middleware in the process of this live-coding. Will fix this week and maybe shoot a video about it.
