### ISSUE TITLE
Do I need to overwrite the default Laravel files? 

### ISSUE THREAD

**Issue by Nemofinsh** [LaravelDaily/Landlord-Tenants-Laravel#3]
Sorry new to here.

After I git clone the files, should I just copy all file into the laravel docs folder and overwrite as well?

Thanks

**Comment by PovilasKorop** [comment]
@Nemofinsh it's a full Laravel project here, you don't need any other Laravel files or copy from somewhere else. Just Clone and use this.

**Comment by Nemofinsh** [comment]
Thanks!

When I clone into all the file and open my site. getting the following errors.

Warning: require(/data/wwwroot/mysite/laravel/public/../vendor/autoload.php): failed to open stream: No such file or directory in /data/wwwroot/mysite/laravel/public/index.php on line 24

Fatal error: require(): Failed opening required '/data/wwwroot/mysite/laravel/public/../vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /data/wwwroot/mysite/laravel/public/index.php on line 24

**Comment by Nemofinsh** [comment]
issue resolved by 
https://stackoverflow.com/questions/28468625/laravel-5-failed-opening-required-bootstrap-vendor-autoload-php

**Comment by PovilasKorop** [comment]
@Nemofinsh yes you probably didn't run `composer install` or `composer update`

**Comment by Nemofinsh** [comment]
sorry got another problem.

when I open as www.domainname , it rewrites to www.domainname/admin/home which fails to open

If i open as www.domainname/index.php then its OK but all js and css fail to load as all become www.domainname/index.php/adminlte/ js or css file url

**Comment by PovilasKorop** [comment]
@Nemofinsh you need to set up your public folder on your domain (probably in `.env` file in APP_URL variable), and rewrite url rules in `.htaccess` or Nginx configuration, depending on your server.

Sorry please read official Laravel documentation on this, it's basics to install Laravel applications, we don't really teach this here.
